### PR TITLE
SPI 2.1

### PR DESCRIPTION
**Pull request by mgouline**
- New SPI features
- Model refactors
- Trim and deprecate obsolete calls

### CODE REVIEW

**Comment by ellulpatrick** [comment]
Missing port - this bug fix should apply also to java

Fixing bug whereby Spi is disposed, but still gets a callback from underlying connection about it being disconnected.
It was trying to connect again because it was still in PairedX state.
Commit:
baf7123cd5441fad14396505658d51eee5052fca [baf7123]
Parents:
31323f3b07
Author:
Patrick Ellul <pellul@assemblypayments.com>
Date:
6 March 2018 at 10:38:42 am AEDT

**Comment by ellulpatrick** [comment]
--> Part Missing Port

1. GLTResponse op_in_progress should so partial match: .StartsWith...
2. _handleGetLastTransactionResponse - missing some complexity around 4E - worth while doing an a/b comparison of this method again. crucial piece of work

first cut of recovery improvement
Commit:
3a1c56722ff80e25fa0cd3ced844344de7b2f99c [3a1c567]
Parents:
157dd3d1e7
Author:
Patrick Ellul <pellul@assemblypayments.com>
Date:
26 March 2018 at 3:33:17 pm AEDT

**Comment by ellulpatrick** [comment]
-->Part missing port
1. missing getErrorDetail on Message

minor getter alterations
Commit:
d4189addc529884a9c77d2d63eff19cdcc31be45 [d4189ad]
Parents:
c283252600
Author:
Patrick Ellul <pellul@assemblypayments.com>
Date:
3 April 2018 at 10:24:26 am AEST

**Comment by ellulpatrick** [comment]
--> this check should also happen in java

guarding against receiving an encrypted message when we don;t have secrets, such as a key_check after we've cancelled pairing just before we disconnect.
Commit:
3fbc9f2710ec3d59ff804e229a1f53534ebab4d6 [3fbc9f2]
Parents:
d3b70f62f7
Author:
Patrick Ellul <pellul@assemblypayments.com>
Date:
18 April 2018 at 9:31:58 am AEST

**Comment by mgouline** [comment]
Ready to be reviewed again, @ellulpatrick.

**Comment by ellulpatrick** [comment]
looks good to me. except for "gtl"->"glt"

**Pull request merged**
